### ISSUE TITLE
Validate configuration against JSON schema

### ISSUE THREAD

**Issue by bebraw** [survivejs/webpack-doctor#1]
I'm not sure if official schema exists for configuration yet. Regardless just doing this would help to point out some common issues (misnamed data and so on).

**Comment by christianalfoni** [comment]
Hm, interesting suggestion, though I think a collection of examples might be more valuable. If you got the skills to create a custom configuration you probably do not need to validate. Just a thought, but cool idea indeed :-)

**Comment by bebraw** [comment]
Yeah, I expect this tool would be valuable esp. for beginner/intermediate level users. It's so easy to miss things when starting out.

**Comment by bebraw** [comment]
[webpack-validator](https://github.com/jonathanewerner/webpack-validator) does this now.
